import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import ToastProvider from '@/components/Application/ToastProvider'

const robotFont = Roboto({
    weight: ['100', '300', '400', '700', '900'],
    display: 'swap',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'E-commerce',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${robotFont.className} antialiased`}>
                <ToastProvider />
                {children}
            </body>
        </html>
    )
}
